#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Export Git hook params
export GIT_PARAMS=$*

npx --no-install fabric verify-commit

if [ -f ".git/hooks/commit-msg" ]; then 
  .git/hooks/commit-msg "$1"
fi
